files:
- generatedChecksum: 53D3B60104FECC78DFF0420732F60DF7
  logicalPath: ''
  name: app_sqi.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: 53D3B60104FECC78DFF0420732F60DF7
- generatedChecksum: A7B4FFBDDBD03C68A00FECFBE7CF9C61
  logicalPath: ''
  name: app_sw_led.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: A7B4FFBDDBD03C68A00FECFBE7CF9C61
- generatedChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
  logicalPath: config/pic32mz_efm_curiosity_v2/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
- generatedChecksum: 479D3F2FF6900275CD72549F38CD37F7
  logicalPath: config/pic32mz_efm_curiosity_v2/driver/sst26
  name: drv_sst26.c
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 479D3F2FF6900275CD72549F38CD37F7
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 2DE38C89EEC773CFF9E21819393007B5
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2DE38C89EEC773CFF9E21819393007B5
- generatedChecksum: B510666BA9257B66995ABBDD33609214
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B510666BA9257B66995ABBDD33609214
- generatedChecksum: F81A00E640818EDFB9E79C9BD241AEF4
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: F81A00E640818EDFB9E79C9BD241AEF4
- generatedChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/cache
  name: plib_cache.c
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 65A7BD3CB0B8FE05768B2EC9A503C3AB
- generatedChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/cache
  name: plib_cache_local.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4FD2B20C75E8ABCE5AFD77297FA520F4
- generatedChecksum: 0DA10C8889278A796D0EE4C6096B57C3
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/cache
  name: plib_cache_pic32mz.S
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0DA10C8889278A796D0EE4C6096B57C3
- generatedChecksum: C6392F1E2B1A11CB0B0F47A0BB017330
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: C6392F1E2B1A11CB0B0F47A0BB017330
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 71684FA1CA06F5EE779CEFD7ADE4A6F7
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71684FA1CA06F5EE779CEFD7ADE4A6F7
- generatedChecksum: 4C6E2B6C48A00D477A193342F820C45F
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4C6E2B6C48A00D477A193342F820C45F
- generatedChecksum: A2E207D459736D20CF2C38D551EE1A99
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/sqi
  name: plib_sqi1.c
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2E207D459736D20CF2C38D551EE1A99
- generatedChecksum: B23CF9B999661031C69C69CB244B3AB8
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: B23CF9B999661031C69C69CB244B3AB8
- generatedChecksum: 47204A328D6218B0241B5993D3198668
  logicalPath: config/pic32mz_efm_curiosity_v2/system/cache
  name: sys_cache.c
  physicalPath: system/cache
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47204A328D6218B0241B5993D3198668
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_efm_curiosity_v2/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
  logicalPath: config/pic32mz_efm_curiosity_v2/system/time
  name: sys_time.c
  physicalPath: system/time/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
- generatedChecksum: F3676FFD1313EA18893FBE4AC55FC45D
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F3676FFD1313EA18893FBE4AC55FC45D
- generatedChecksum: AEAD678D52A900BF13F45EFDA811BC10
  logicalPath: config/pic32mz_efm_curiosity_v2/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEAD678D52A900BF13F45EFDA811BC10
- generatedChecksum: 3F23CD30C5BC97A320F08676C897E402
  logicalPath: ''
  name: app_sqi.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F23CD30C5BC97A320F08676C897E402
- generatedChecksum: 3CE38E9947C89E8E0186CA46D1BB1D3F
  logicalPath: ''
  name: app_sw_led.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: 3CE38E9947C89E8E0186CA46D1BB1D3F
- generatedChecksum: 3A3D90BBDFDB486B57C8FED3BA7D4135
  logicalPath: config/pic32mz_efm_curiosity_v2/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A3D90BBDFDB486B57C8FED3BA7D4135
- generatedChecksum: 4D1AF62E9DD9BA35330754CD3DDA1ED4
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D1AF62E9DD9BA35330754CD3DDA1ED4
- generatedChecksum: BAC244FF41BAD9E21D4312D5068129C6
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: BAC244FF41BAD9E21D4312D5068129C6
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CA1C2C02834207DCB4B0E3C00338FCC
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_efm_curiosity_v2/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_efm_curiosity_v2/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 8EAE086FFBCC60C4343BAA26620B1204
  logicalPath: config/pic32mz_efm_curiosity_v2/driver/sst26
  name: drv_sst26.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: 8EAE086FFBCC60C4343BAA26620B1204
- generatedChecksum: D712283D4ED135C84E162B40760A9C23
  logicalPath: config/pic32mz_efm_curiosity_v2/driver/sst26
  name: drv_sst26_definitions.h
  physicalPath: driver/sst26
  security: NON_SECURE
  type: HEADER
  userChecksum: D712283D4ED135C84E162B40760A9C23
- generatedChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
  logicalPath: config/pic32mz_efm_curiosity_v2/driver/sst26
  name: drv_sst26_local.h
  physicalPath: driver/sst26/src
  security: NON_SECURE
  type: HEADER
  userChecksum: D0F58EA0E69F1EC3040F9EB3C64B9737
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_efm_curiosity_v2/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_efm_curiosity_v2/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_efm_curiosity_v2/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 37885E3505BF5B0FD6AFE768807361C1
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/cache
  name: plib_cache.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 37885E3505BF5B0FD6AFE768807361C1
- generatedChecksum: 3D2558D7758EF020BBF792820203C0A2
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/cache
  name: plib_cache_pic32mz.h
  physicalPath: peripheral/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: 3D2558D7758EF020BBF792820203C0A2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: 815CCB981B6CB758464D89480121DC08
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 815CCB981B6CB758464D89480121DC08
- generatedChecksum: 4C4DFAAE6CE4913653A36AB02F9B8C73
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C4DFAAE6CE4913653A36AB02F9B8C73
- generatedChecksum: 83A29BB1714DD4AF71B7176C4A487262
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/sqi
  name: plib_sqi1.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: 83A29BB1714DD4AF71B7176C4A487262
- generatedChecksum: BA2AAEA19E581F59C1E78E73982F7C78
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/sqi
  name: plib_sqi_common.h
  physicalPath: peripheral/sqi
  security: NON_SECURE
  type: HEADER
  userChecksum: BA2AAEA19E581F59C1E78E73982F7C78
- generatedChecksum: BF528AAAE932C4E5F2A80A7DEF4C80F8
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: BF528AAAE932C4E5F2A80A7DEF4C80F8
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_efm_curiosity_v2/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: AFAAF7D896D57569CA4CF73BB3339481
  logicalPath: config/pic32mz_efm_curiosity_v2/system/cache
  name: sys_cache.h
  physicalPath: system/cache
  security: NON_SECURE
  type: HEADER
  userChecksum: AFAAF7D896D57569CA4CF73BB3339481
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mz_efm_curiosity_v2/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_efm_curiosity_v2/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_efm_curiosity_v2/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 6348A6C05D5693300B296BD46CCC535D
  logicalPath: config/pic32mz_efm_curiosity_v2/system/ports
  name: sys_ports.h
  physicalPath: system/ports
  security: NON_SECURE
  type: HEADER
  userChecksum: 6348A6C05D5693300B296BD46CCC535D
- generatedChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
  logicalPath: config/pic32mz_efm_curiosity_v2/system/ports
  name: sys_ports_mapping.h
  physicalPath: system/ports
  security: NON_SECURE
  type: HEADER
  userChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config/pic32mz_efm_curiosity_v2/system/time
  name: sys_time.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config/pic32mz_efm_curiosity_v2/system/time
  name: sys_time_definitions.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config/pic32mz_efm_curiosity_v2/system/time
  name: sys_time_local.h
  physicalPath: system/time/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_efm_curiosity_v2/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_efm_curiosity_v2/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_efm_curiosity_v2/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 4B3C3EF8A318908A22B78500515C3288
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B3C3EF8A318908A22B78500515C3288
- generatedChecksum: 07A482DAB7473FC475EA656561967B15
  logicalPath: config/pic32mz_efm_curiosity_v2
  name: p32MZ2048EFM144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 07A482DAB7473FC475EA656561967B15
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_efm_curiosity_v2;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_efm_curiosity_v2;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
